### ISSUE TITLE
Add a way to search uk tickets too 

### ISSUE THREAD

**Issue by Josee-xav** [tducret/trainline-python#12]
Need a way to switch to https://www.trainline.com 

:)

**Comment by tducret** [comment]
Hello @danieljo12 
Unfortunately trainline.fr and thetrainline.com have completely different API :/
The French branch was bought from captaintrain but I'm affraid they didn't merge their backend... yet.

**Comment by alxch-** [comment]
On trainline.fr there is a banner saying that they are switching to thetrainline.com (see [this FAQ](https://www.thetrainline.com/fr/aide/question/6537/beta)). So I guess they're merging their backends and trainline.fr might be deprecated in the future.

**Comment by tducret** [comment]
You're right, sorry @danieljo12 :/
Thank you for the update @alxch- , I didn't know about it.
I'll definitively take a closer look then :)
