### ISSUE TITLE
CAPCHA Error

### ISSUE THREAD

**Issue by jfg** [tducret/trainline-python#20]
* trainline version: latest
* Python version: Python 3.9.7
* Operating System: macOS Monterey 12.0.1

### Description

I have an error when i run this command :

~ % docker run -it --rm thibdct/trainline --departure="Toulouse" --arrival="Bordeaux" --next=12hours
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/app/bin/trainline_cli.py", line 104, in <module>
    main()
  File "/app/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/app/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/app/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/bin/trainline_cli.py", line 75, in main
    transportation_mean=transport)
  File "/app/trainline/__init__.py", line 606, in search
    passenger_list=passenger_list)
  File "/app/trainline/__init__.py", line 129, in search
    ret = c._post(url=_SEARCH_URL, post_data=post_data)
  File "/app/trainline/__init__.py", line 83, in _post
    status=ret.status_code, url=url, content=ret.text))
requests.exceptions.ConnectionError: Status code 403 for url https://www.trainline.eu/api/v5_1/search
{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAr6iE4AJKYw4AWKiFGA==&cid=Qbdi60vxNjrCR_UO36tp0APJHQ_iwdN.4iMl9FpBj~e9_9tSqHhvYZs0VwG43PYeMD9Drei0Uj0jn34rWgnYzLl1P0cjqyTwuHb4O.EqKm&referer=HTTPS%3A%2F%2Fwww.trainline.eu%2Fapi%2Fv5_1%2Fsearch&hash=E1950F58FF4C3B67C237DE42A4D080&t=fe&s=35668"}

### What I Did
run this command : 
docker run** -it --rm thibdct/trainline --departure="Toulouse" --arrival="Bordeaux" --next=12hours

Thanks for your help

**Comment by tducret** [comment]
Well, it seems that Trainline has improved its anti-scraping measures :/
We didn't intend to counter captchas with this package, so I don't really know how to solve this issue.

**Comment by jfg** [comment]
Ok, too bad..
Thanks for your return.
