### ISSUE TITLE
Crash sur certaines dates

### ISSUE THREAD

**Issue by yann120** [tducret/trainline-python#4]
* trainline version: last
* Python version: Python 3.5.3
* Operating System: Debian

### Description

Bonjour, j'essaye le script sur différentes dates, certaines comme aujourd'hui fonctionnent mais certaines dans le futur non. Le programme crash

### What I Did
Voici mon code
`# -*- coding: utf-8 -*-
import trainline

Yann = trainline.Passenger(birthdate="04/07/1994")

results = trainline.search(
        passengers=[Yann],
        departure_station="paris",
        arrival_station="nice",
        from_date="21/06/2019 08:00",
        to_date="21/06/2019 21:00")

print(results.csv())`

et voici l'erreur quand je lance la commande 
`Traceback (most recent call last):
  File "test_trainline/test2.py", line 11, in <module>
    to_date="21/06/2019 21:00")
  File "/home/yann/.local/lib/python3.5/site-packages/trainline/__init__.py", line 596, in search
    folders = _get_folders(search_results_obj=j)
  File "/home/yann/.local/lib/python3.5/site-packages/trainline/__init__.py", line 648, in _get_folders
    trip_obj_list = _get_trips(search_results_obj)
  File "/home/yann/.local/lib/python3.5/site-packages/trainline/__init__.py", line 681, in _get_trips
    segment_obj_list = _get_segments(search_results_obj)
  File "/home/yann/.local/lib/python3.5/site-packages/trainline/__init__.py", line 724, in _get_segments
    comfort_class_obj_list = _get_comfort_classes(search_results_obj)
  File "/home/yann/.local/lib/python3.5/site-packages/trainline/__init__.py", line 796, in _get_comfort_classes
    comfort_class_obj = ComfortClass(dict_comfort_class)
  File "/home/yann/.local/lib/python3.5/site-packages/trainline/__init__.py", line 478, in __init__
    for extra in self.extras:
TypeError: 'NoneType' object is not iterable`

En revanche, si je change from_date "21/06/2019 08:00" pour "10/06/2019 08:00" et to_date "21/06/2019 21:00" pour "10/06/2019 21:00", ca fonctionne bien.
Très bizarre car les dates on l'air pourtant bonne...

Sinon bravo pour ton travail, j'ai regardé ton code, c'est très intéressant! :) 
Merci d'avance!

**Comment by yann120** [comment]
Et chose encore plus drole, les mêmes dates foireuses avec un Toulouse - Bordeaux fonctionnent! À croire que tu privilégie ta région ;-)
Merci encore!

**Comment by tducret** [comment]
Salut Yann! Merci pour ton retour. Je pense avoir trouvé le problème.
Peux-tu passer à la version `0.0.8` du package et tester stp?

**Comment by yann120** [comment]
Salut, merci pour ta réactivité!
Ça fonctionne maintenant, c'est parfait!
Merci beaucoup pour ton travail, ton parsing m'aide beaucoup pour faire mon script qui me permet trouver des places TGVMAX qui se libèrent.
Je viens de le finir et je vais maintenant faire tourner ça sur mon serveur :)

**Comment by tducret** [comment]
Merci à toi.
C'est marrant de voir du Python utilisé dans du Ruby :)
