### ISSUE TITLE
Tarif TGVmax non pris en compte

### ISSUE THREAD

**Issue by sebbastien** [tducret/trainline-python#5]
* trainline version: 0.0.8

Hey, 

First of all, very nice and usefull code !! 
I have an issue when I specify my TGVmax id card, I get all the train of my period except all of them which are set at 0.0€. 
Do you know how to list even a train with a price set to 0.0€ ? Which are them I looking for.
I tried to modify the min_price and the filter loop, but can't find a solution.

Thanks a lot,
Regards.

**Comment by tducret** [comment]
Hi @sebbastien 
Thanks for the feedback. Strange issue :/
Unfortunately, without a valid TGVmax id, I cannot reproduce it or investigate.
@baptiste-mnh Can you have a look at it?

**Comment by baptiste-mnh** [comment]
Hi!
I think i found the issue but will investigate it asap.
Can you try to set the max_price in the search method to 1 ?

**Comment by sebbastien** [comment]
Hi, I set the max_price equal to 1 in line 568 or/and line 815 but for both case no result are found and nothing is printed except the first line: 'departure_date;arrival_date;duration;number_of_segments;price;currency;transportation_mean;bicycle_reservation'

Let me know if you want I try something else.

**Comment by baptiste-mnh** [comment]
First check [here](https://simulateur.tgvmax.fr/VSC) if a tgvmax is available and then search the train at the same date if the train is available or not from the this API.

Furthermore, do not modify the code to modify the max_price, it's already set in search function parameters.
If it still doesn't work I'll have a closer look on the issue.

**Comment by sebbastien** [comment]
For example, I look for Paris->Marseille on the 12/06/2019. On https://simulateur.tgvmax.fr/VSC/#/1 the 18h37 and 20h19 are available. And also available on Trainline.fr.
Below you can look at the results when I ran trainline python with my TGVmax id card and no change in the code:
 - python3 main.py Paris Marseille '12/06/2019 14:00' '12/06/2019 23:59'
departure_date;arrival_date;duration;number_of_segments;price;currency;transportation_mean;bicycle_reservation
12/06/2019 14:30;13/06/2019 18:30;04h00;1;55,0;EUR;coach;unavailable
12/06/2019 14:37;12/06/2019 17:55;03h18;1;45,0;EUR;train;unavailable
12/06/2019 15:07;12/06/2019 18:16;03h09;1;98,0;EUR;train;unavailable
12/06/2019 15:07;12/06/2019 18:16;03h09;1;149,0;EUR;train;unavailable
12/06/2019 15:07;12/06/2019 18:16;03h09;1;160,0;EUR;train;unavailable
12/06/2019 15:37;12/06/2019 18:55;03h18;1;116,0;EUR;train;unavailable
12/06/2019 15:37;12/06/2019 18:55;03h18;1;135,0;EUR;train;unavailable
12/06/2019 15:37;12/06/2019 18:55;03h18;1;160,0;EUR;train;unavailable
12/06/2019 16:15;12/06/2019 19:20;03h05;1;160,0;EUR;train;unavailable
12/06/2019 16:15;12/06/2019 19:20;03h05;1;113,0;EUR;train;unavailable
12/06/2019 16:15;12/06/2019 19:20;03h05;1;89,0;EUR;train;unavailable
12/06/2019 16:37;12/06/2019 19:56;03h19;1;156,0;EUR;train;unavailable
12/06/2019 16:37;12/06/2019 19:56;03h19;1;89,0;EUR;train;unavailable
12/06/2019 16:37;12/06/2019 19:56;03h19;1;160,0;EUR;train;unavailable
12/06/2019 17:37;12/06/2019 20:55;03h18;1;122,0;EUR;train;unavailable
12/06/2019 17:37;12/06/2019 20:55;03h18;1;98,0;EUR;train;unavailable
12/06/2019 17:37;12/06/2019 20:55;03h18;1;160,0;EUR;train;unavailable
12/06/2019 23:20;13/06/2019 11:30;12h10;1;19,98;EUR;coach;unavailable
12/06/2019 23:20;13/06/2019 08:14;08h54;2;62,99;EUR;train+coach;unavailable
12/06/2019 23:20;13/06/2019 08:14;08h54;2;66,99;EUR;train+coach;unavailable
12/06/2019 23:20;13/06/2019 08:55;09h35;2;30,99;EUR;train+coach;unavailable

And here it's the result when I ran with max_price=1 in main.py:
 - python3 main.py Paris Marseille '12/06/2019 14:00' '12/06/2019 23:59'
departure_date;arrival_date;duration;number_of_segments;price;currency;transportation_mean;bicycle_reservation

So still the same issue... Sorry.

**Comment by baptiste-mnh** [comment]
Can you try this way?
```python
user = trainline.Passenger(birthdate="01/01/1996", cards=[trainline.JEUNE])
user.add_special_card(trainline.TGVMAX, "YOUR_CARD_ID")

results = trainline.search(
passengers=[user],
departure_station="Paris",
arrival_station="Paris",
from_date="01/05/2019 05:00",
to_date="01/05/2019 9:00",
max_price=0.0)

print(results.csv())
```

**Comment by sebbastien** [comment]
Instead of using your lines I used these ones in main.py (I changed the date:

```python
user = trainline.Passenger(birthdate="01/01/1996", cards=[trainline.JEUNE])
user.add_special_card(trainline.TGVMAX, "HC000XXXXXX")

results = trainline.search(
passengers=[user],
departure_station="Paris",
arrival_station="Marseille",
from_date="12/06/2019 14:00",
to_date="12/06/2019 23:59",
max_price=0.0)

print(results.csv())
```
Then run the command:
```python
python3 main.py Paris Marseille '12/06/2019 14:00' '12/06/2019 23:59'
```
It gives the following output:
`departure_date;arrival_date;duration;number_of_segments;price;currency;transportation_mean;bicycle_reservation`

So still no change. Is there a way to print all the outputs from the API? Maybe the API do not show tgvmax tickets, but if tgvmax tickets are printed out, it means that the error comes from post processing.

**Comment by baptiste-mnh** [comment]
Ok, weird... I will check.

**Comment by alxch-** [comment]
When looking for a large timeframe, (such as `from_date="12/06/2019 14:00", to_date="12/06/2019 23:59"`) it does not work. However when testing with something like `from_date="12/06/2019 20:00", to_date="12/06/2019 23:59"`, it works well. With this smaller timeframe it displays:
```
12/06/2019 20:19;12/06/2019 23:42;03h23;1;0,0;EUR;train;unavailable
```
So there may be an issue with the requests to cover the full timeframe? It works when setting `from_date="12/06/2019 18:00"`, but not before.

**Comment by benoitdemaegdt** [comment]
Hey !
Just to let you know that I tried it this morning, and it worked perfectly fine.

index.py (in the project's root) : 
```python
# -*- coding: utf-8 -*-
import trainline
from trainline import Trainline, Trip, Passenger, Segment, ComfortClass, Folder

user = trainline.Passenger(birthdate="01/08/1994")
user.add_special_card(trainline.TGVMAX, "HC00XXXXXXX")

from_date = "01/10/2019 07:00"
to_date = "01/10/2019 20:00"
departure_station = "paris"
arrival_station = "lyon part-dieu"

results = trainline.search(
    passengers=[user],
    departure_station=departure_station,
    arrival_station=arrival_station,
    from_date=from_date,
    to_date=to_date,
    max_price=0.0)

print(results.csv())
```
Then run : 
```bash
python3 index.py > file.csv
```

As you can see the timeframe is large, and I got all the trains that have a TGVmax seat available (I backtested with the oui.sncf app 👌 ).

<img width="701" alt="trainline-python" src="https://user-images.githubusercontent.com/25749578/65750282-49767a00-e108-11e9-9332-1c09fb227261.png">

Thank you to the people who made this package ! 👏  😊

**Comment by tducret** [comment]
Thanks for the feedback @benoitdemaegdt
