### ISSUE TITLE
Duplicates in stations_mini.csv

### ISSUE THREAD

**Issue by alxch-** [tducret/trainline-python#6]
* trainline version: 0.0.8
* Python version: 3.7
* Operating System: MacOS 

### Description

`stations_mini.csv` is generated from the `stations.csv` from Trainline, but it seems that this file contains duplicates. For example, there seems to be two stations for Rennes which are duplicated in the `stations.csv` file too: `5055` (https://github.com/tducret/trainline-python/blob/master/trainline/stations_mini.csv#L3807) and `5097` (https://github.com/tducret/trainline-python/blob/master/trainline/stations_mini.csv#L3833). However, the `get_station_id` returns the first occurence in the `stations_mini.csv`, which sometimes returns no result from the trainline API.
Some stations are marked as `suggestable` in `stations.csv`. From what I understand, Trainline API will result results only for these stations.
I am going to open a PR to generate `stations_mini.csv` only for stations having the `is_suggestable` set to True. The README (https://github.com/trainline-eu/stations) indicates that `is_suggestable` means : `Specify if the user can input this station.`

### What I Did

```
user = trainline.Passenger(birthdate="01/01/1996", cards=[trainline.JEUNE])
s = trainline.search( passengers=[user], departure_station="Paris", arrival_station="Rennes", from_date="18/06/2019 11:00", to_date="18/06/2019 15:00")
```
I got:
```
Status code 400 for url https://www.trainline.eu/api/v5_1/search
{"error":"Nous n’avons trouvé aucun trajet à cet horaire.","code":"no_results"}
```

**Comment by alxch-** [comment]
PR with fix is here: https://github.com/tducret/trainline-python/pull/7

**Comment by tducret** [comment]
Thank you very much @alxch- 
I had no idea about the `is_suggestable` tag 😯
